### ISSUE TITLE
Should Resizing Horizontally Work the Same Way On Mobile?

### ISSUE THREAD

**Issue by Trang12345** [MrHombre/Zoom-Out-Responsive-Landing-Page#1]
I just cloned this and deployed it to Heroku. I noticed that when I view the website on my phone it doesn't look the same as when I resize the window horizontally to be really small on my computer. Is it supposed to / do you know why that is?

**Comment by OatsandToast** [comment]
So I haven't looked at this project in quite some time, but are you talking about this? 
![2017-01-07_15h38_11](https://cloud.githubusercontent.com/assets/12551985/21746232/c138362a-d4f2-11e6-8460-4dee828fc239.png)
When on mobile it doesn't respond like it should? If so, I think this has to do with the _layout/_variables.scss in the partials folder. It definitely isn't being responsive, at least not on mobile. So if you want to mess around that would probably be where I would start. I also check the js file, I remember getting some help, so the problem could also be there.

Last but not least, I hope you're not using this as a guide or anything like that, this project was not at all meant to be helpful for anyone lol.

**Comment by OatsandToast** [comment]
If there is something else you would like to know, just say so! I'll leave this open for a day or two just in case.

**Comment by Trang12345** [comment]
I was hoping it would look better on mobile but that is ok. Thanks for responding.
